INSERT INTO pertanyaan (id, pertanyaan) VALUES 
('Q01', 'Apakah Anda sangat menikmati aktivitas coding (menulis kode) untuk memecahkan masalah logika algoritma?'),
('Q02', 'Apakah Anda tertarik mempelajari berbagai framework pengembangan aplikasi (seperti Laravel, React, Flutter)?'),
('Q03', 'Apakah Anda lebih suka menganalisis kebutuhan bisnis dan merancang diagram alur sistem (ERD, DFD, UML) dibanding menulis kode?'),
('Q04', 'Apakah Anda memiliki kemampuan komunikasi yang baik untuk menjadi jembatan antara klien/pengguna dengan tim teknis?'),
('Q05', 'Apakah Anda sangat peduli pada estetika, komposisi warna, dan kenyamanan visual dalam sebuah aplikasi?'),
('Q06', 'Apakah Anda mahir menggunakan tools prototyping desain seperti Figma, Adobe XD, atau Sketch?'),
('Q07', 'Apakah Anda tertarik pada logika fisika, matematika vektor, atau AI yang diterapkan pada pergerakan karakter virtual?'),
('Q08', 'Apakah Anda antusias menggunakan Game Engine (seperti Unity atau Unreal Engine) untuk membangun dunia interaktif?'),
('Q09', 'Apakah Anda menyukai pekerjaan fisik merancang topologi jaringan (LAN/WAN) dan pengkabelan?'),
('Q10', 'Apakah Anda menguasai konfigurasi perangkat keras jaringan seperti Router (Mikrotik/Cisco) dan Switch?'),
('Q11', 'Apakah Anda gemar mengelola Sistem Operasi Server (Linux/Windows Server) berbasis perintah teks (CLI)?'),
('Q12', 'Apakah Anda tertarik pada manajemen pengguna (User Management), instalasi, dan pemeliharaan rutin server?'),
('Q13', 'Apakah Anda merasa tertantang saat melakukan debugging pada sesuatu yang kompleks?'),
('Q14', 'Apakah Anda tertarik memastikan server dan jaringan tetap berjalan stabil (uptime) selama 24 jam?'),
('Q15', 'Apakah Anda sering memikirkan bagaimana cara pengguna berinteraksi dengan tombol atau menu agar tidak membingungkan?'),
('Q16', 'Apakah Anda tertarik mendokumentasikan spesifikasi teknis agar mudah dipahami oleh programmer?'),
('Q17', 'Apakah Anda merasa nyaman merancang struktur database yang efisien dan melakukan optimasi query?'),
('Q18', 'Apakah Anda paham konsep keamanan jaringan seperti firewall, IDS/IPS, dan VPN?'),
('Q19', 'Apakah Anda sering membuat flowchart atau diagram logika sebelum membangun aplikasi?'),
('Q20', 'Apakah Anda antusias melakukan otomasi server menggunakan scripting (Bash, PowerShell, Python)?'),
('Q21', 'Apakah Anda tertarik mempelajari serta membuat analisis bisnis untuk menentukan solusi teknologi yang tepat?'),
('Q22', 'Apakah Anda sering mengeksplorasi teknik animasi dan efek visual untuk pengalaman game yang lebih menarik?');