INSERT INTO profil (id, profil) VALUES 
('P01', 'SOFTWARE DEVELOPER'),
('P02', 'SYSTEM ANALYST'),
('P03', 'UI / UX DESIGNER'),
('P04', 'GAME DEVELOPER'),
('P05', 'NETWORK ENGINEER'),
('P06', 'SYSTEM ADMINISTRATOR');